[logger]
level = "info"

[connection]
login = "guest"
password = "guest"
host = "localhost"
port = "5672"

[consume]
queue = "notification"
consumer = ""
autoAck = true
exclusive = false
noLocal = false
noWait = false

[queue]
name = "notification"
durable = false
autoDelete = false
exclusive = false
noWait = false

